---
# tasks file for yolo-backend
- name: Install app dependencies defined in package.json.
  npm: "path={{ yolo_backend_location }}"



- name: Start backend app.
  shell: | 
    chdir={{ yolo_backend_location }}
    forever start -c "npm start" ./