---
# tasks file for yolo-frontend
- block:
    - name: Pull default Docker image
    
      community.general.docker_image:
        name: haxor44/yolo-client:v1.0.0
        source: pull

    - name: Create yolo frontend client container
      community.docker.docker_container:
        name: yolo-client
        image: haxor44/yolo-client:v1.0.0
        state: present
        ports:
              - "3000:3000"
  become: yes