---
# tasks file for yolo-frontend
- name: Install app dependencies defined in package.json.
  npm: "path={{ yolo_client_location }}"

  # shell: | 
  #   chdir=/home/vagrant/projects/stage_two/client/   
  #   npm install 
- name: "Install forever (to run Node.js app)."
  npm: name=forever global=yes state=present

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

# - name: "Start example Node.js app."
#   command: 
 


- name: Start client Node.js app.
  shell: | 
    chdir={{ yolo_client_location }}
    forever start -c "npm start" ./