apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: haxor44/yolo-backend:v1.0.0
        env:
          - name: "DBHOST"
            value: db-service
        resources:
          limits:
            memory: "512Mi"
            cpu: "900m"
        ports:
        - containerPort: 5000
