apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        resources:
          limits:
            memory: "512Mi"
            cpu: "900m"
        ports:
        - containerPort: 27017
