apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongo_db
  template:
    metadata:
      labels:
        app: mongo_db
    spec:
      containers:
      - name: mongo_db
        image: mongo:4.4
        resources:
          limits:
            memory: "512Mi"
            cpu: "900m"
        ports:
        - containerPort: 27017
